#!/usr/bin/env python3
"""Empirical probe: Rust `regex` crate vs raw bundled PCRE2 (8-bit).

Gilfoyle prove-it evidence only. This script never edits production code:
it generates a fresh temporary Cargo crate pinned to regex =1.13.1 and
pcre2-sys =0.2.10, builds it (bundled PCRE2), runs it, and emits exactly one
deterministic JSON object. All state is temporary; on any subprocess failure
the captured stderr is written to stderr and the process exits nonzero
(never a plausible false result).

The generated Rust program reports:
  - whether rust regex rejects (?<=foo)bar (and the error text),
  - whether PCRE2 8-bit compiles it and matches "bar" in "foobar" (span),
  - the typed return codes of pcre2_set_match_limit_8 / pcre2_set_depth_limit_8,
  - the typed PCRE2 return codes of deterministic match-limit and depth-limit
    exhaustion patterns (PCRE2_ERROR_MATCHLIMIT / PCRE2_ERROR_DEPTHLIMIT),
  - the target triple, and bundled build/link/run success by virtue of running.
"""

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

REGEX_PIN = "1.13.1"
PCRE2_SYS_PIN = "0.2.10"
CARGO_TIMEOUT_SECONDS = 1800

CARGO_TOML = f"""\
[package]
name = "pcre2-probe"
version = "0.0.0"
edition = "2021"

[workspace]

[dependencies]
regex = "={REGEX_PIN}"
pcre2-sys = "={PCRE2_SYS_PIN}"
"""

BUILD_RS = """\
fn main() {
    let target = std::env::var("TARGET").expect("cargo sets TARGET for build scripts");
    println!("cargo:rustc-env=OMI_TARGET_TRIPLE={}", target);
}
"""

MAIN_RS = r"""//! Empirical probe: `regex` crate vs raw PCRE2 (8-bit) behavior.
//!
//! Generated by .rfs-vl0u/probe_pcre2.py. Prints one deterministic JSON
//! object to stdout. This program running at all is the evidence that the
//! bundled PCRE2 build, link, and run succeeded. No bare unwraps: every
//! invariant check carries a message.

use std::os::raw::c_int;

fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Canonical PCRE2 error name for a typed return code.
fn error_name(code: c_int) -> &'static str {
    match code {
        pcre2_sys::PCRE2_ERROR_NOMATCH => "PCRE2_ERROR_NOMATCH",
        pcre2_sys::PCRE2_ERROR_MATCHLIMIT => "PCRE2_ERROR_MATCHLIMIT",
        pcre2_sys::PCRE2_ERROR_DEPTHLIMIT => "PCRE2_ERROR_DEPTHLIMIT",
        _ => "PCRE2_ERROR_OTHER",
    }
}

struct Json {
    parts: Vec<String>,
}

impl Json {
    fn new() -> Json {
        Json { parts: Vec::new() }
    }
    fn s(&mut self, key: &str, value: &str) {
        self.parts
            .push(format!("{}:{}", json_escape(key), json_escape(value)));
    }
    fn b(&mut self, key: &str, value: bool) {
        self.parts.push(format!("{}:{}", json_escape(key), value));
    }
    fn i(&mut self, key: &str, value: i64) {
        self.parts.push(format!("{}:{}", json_escape(key), value));
    }
    fn opt_i(&mut self, key: &str, value: Option<c_int>) {
        match value {
            Some(v) => self.parts.push(format!("{}:{}", json_escape(key), v)),
            None => self.parts.push(format!("{}:null", json_escape(key))),
        }
    }
    fn opt_span(&mut self, key: &str, value: Option<(usize, usize)>) {
        match value {
            Some((start, end)) => {
                self.parts
                    .push(format!("{}:[{},{}]", json_escape(key), start, end));
            }
            None => {
                self.parts.push(format!("{}:null", json_escape(key)));
            }
        }
    }
    fn finish(self) -> String {
        format!("{{{}}}", self.parts.join(","))
    }
}

/// Compile an 8-bit pattern. Returns the code pointer, or (errorcode, offset).
fn compile(pattern: &[u8], options: u32) -> Result<*mut pcre2_sys::pcre2_code_8, (c_int, usize)> {
    let mut errorcode: c_int = 0;
    let mut erroroffset: usize = 0;
    let code = unsafe {
        pcre2_sys::pcre2_compile_8(
            pattern.as_ptr(),
            pattern.len(),
            options,
            &mut errorcode,
            &mut erroroffset,
            std::ptr::null_mut(),
        )
    };
    if code.is_null() {
        Err((errorcode, erroroffset))
    } else {
        Ok(code)
    }
}

/// Match `subject` against `code`. Frees the match data it allocates.
/// Returns (rc, matched span) where span is present iff rc >= 0.
fn run_match(
    code: *const pcre2_sys::pcre2_code_8,
    subject: &[u8],
    mcontext: *mut pcre2_sys::pcre2_match_context_8,
) -> (c_int, Option<(usize, usize)>) {
    let md = unsafe {
        pcre2_sys::pcre2_match_data_create_from_pattern_8(code, std::ptr::null_mut())
    };
    assert!(!md.is_null(), "match data allocation must succeed");
    let rc = unsafe {
        pcre2_sys::pcre2_match_8(
            code,
            subject.as_ptr(),
            subject.len(),
            0usize,
            0u32,
            md,
            mcontext,
        )
    };
    let span = if rc >= 0 {
        let ovec = unsafe { pcre2_sys::pcre2_get_ovector_pointer_8(md) };
        assert!(
            !ovec.is_null(),
            "ovector must be valid after a successful match"
        );
        Some((unsafe { *ovec }, unsafe { *ovec.add(1) }))
    } else {
        None
    };
    unsafe {
        pcre2_sys::pcre2_match_data_free_8(md);
    }
    (rc, span)
}

fn main() {
    // --- Rust `regex` crate behavior -------------------------------------
    let (rust_rejects, rust_error) = match regex::Regex::new(r"(?<=foo)bar") {
        Ok(_) => (false, String::new()),
        Err(e) => (true, e.to_string()),
    };
    let rust_control_ok = regex::Regex::new(r"foo")
        .expect("control pattern must compile")
        .is_match("foobar");
    let rust_unicode_casefold_ok = regex::RegexBuilder::new("CAFÉ")
        .case_insensitive(true)
        .build()
        .expect("Unicode case-fold control pattern must compile")
        .is_match("café");

    // --- PCRE2 8-bit behavior --------------------------------------------
    let mcontext =
        unsafe { pcre2_sys::pcre2_match_context_create_8(std::ptr::null_mut()) };
    assert!(!mcontext.is_null(), "match context allocation must succeed");

    let match_limit_set_rc = unsafe { pcre2_sys::pcre2_set_match_limit_8(mcontext, 1000u32) };

    // Lookbehind: compile and match "bar" inside "foobar".
    let (lb_compiled, lb_compile_rc, lb_compile_offset, lb_code) =
        match compile(b"(?<=foo)bar", 0u32) {
            Ok(code) => (true, 0, 0usize, code),
            Err((ec, off)) => (false, ec, off, std::ptr::null_mut()),
        };
    let (lb_match_rc, lb_span) = if lb_compiled {
        run_match(lb_code, b"foobar", mcontext)
    } else {
        (0, None)
    };

    // Match-limit exhaustion: (a+)+ partitions 32 a's before the failing $,
    // so pcre2_match must blow past match_limit=1000 and return -47.
    let ml_code = compile(b"^(a+)+$", 0u32).expect("match-limit pattern must compile");
    let ml_subject: Vec<u8> = std::iter::repeat(b'a')
        .take(32)
        .chain(std::iter::once(b'b'))
        .collect();
    let (ml_rc, _) = run_match(ml_code, &ml_subject, mcontext);

    // Depth-limit exhaustion: (a(?1)?b) recurses once per leading 'a' (20
    // levels needed), so depth_limit=8 must return -53.
    let depth_limit_set_rc = unsafe { pcre2_sys::pcre2_set_depth_limit_8(mcontext, 8u32) };
    let dl_code = compile(b"(a(?1)?b)", 0u32).expect("depth-limit pattern must compile");
    let dl_subject: Vec<u8> = std::iter::repeat(b'a')
        .take(20)
        .chain(std::iter::repeat(b'b').take(20))
        .collect();
    let (dl_rc, _) = run_match(dl_code, &dl_subject, mcontext);
    let unicode_options =
        pcre2_sys::PCRE2_CASELESS | pcre2_sys::PCRE2_UTF | pcre2_sys::PCRE2_UCP;
    let uc_code = compile("CAFÉ".as_bytes(), unicode_options)
        .expect("Unicode case-fold control pattern must compile");
    let (uc_rc, uc_span) = run_match(uc_code, "café".as_bytes(), mcontext);

    // Free every PCRE2 allocation.
    unsafe {
        if lb_compiled {
            pcre2_sys::pcre2_code_free_8(lb_code);
        }
        pcre2_sys::pcre2_code_free_8(ml_code);
        pcre2_sys::pcre2_code_free_8(dl_code);
        pcre2_sys::pcre2_code_free_8(uc_code);
        pcre2_sys::pcre2_match_context_free_8(mcontext);
    }

    let mut j = Json::new();
    j.s("probe", "pcre2");
    j.s("target_triple", env!("OMI_TARGET_TRIPLE"));
    j.b("bundled_build_link_run_ok", true);
    j.b("rust_regex_rejects_lookbehind", rust_rejects);
    j.s("rust_regex_lookbehind_error", &rust_error);
    j.b("rust_regex_control_ok", rust_control_ok);
    j.b("rust_regex_unicode_casefold_ok", rust_unicode_casefold_ok);
    j.b("pcre2_compiles_lookbehind", lb_compiled);
    j.i("pcre2_lookbehind_compile_errorcode", lb_compile_rc as i64);
    j.i("pcre2_lookbehind_compile_erroroffset", lb_compile_offset as i64);
    j.opt_i(
        "pcre2_lookbehind_match_rc",
        if lb_compiled { Some(lb_match_rc) } else { None },
    );
    j.opt_span("pcre2_lookbehind_match_span", lb_span);
    j.i("pcre2_match_limit_set_rc", match_limit_set_rc as i64);
    j.i("pcre2_depth_limit_set_rc", depth_limit_set_rc as i64);
    j.i("pcre2_match_limit_exhaustion_rc", ml_rc as i64);
    j.s("pcre2_match_limit_exhaustion_name", error_name(ml_rc));
    j.i("pcre2_depth_limit_exhaustion_rc", dl_rc as i64);
    j.s("pcre2_depth_limit_exhaustion_name", error_name(dl_rc));
    j.b("pcre2_unicode_casefold_ok", uc_rc >= 0);
    j.opt_span("pcre2_unicode_casefold_span", uc_span);
    println!("{}", j.finish());
}
"""


def run_or_die(cmd, cwd, what, env):
    try:
        proc = subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=CARGO_TIMEOUT_SECONDS,
            env=env,
        )
    except FileNotFoundError:
        sys.stderr.write(f"fatal: {what}: executable not found: {cmd[0]}\n")
        sys.exit(1)
    except subprocess.TimeoutExpired:
        sys.stderr.write(f"fatal: {what}: timed out after {CARGO_TIMEOUT_SECONDS}s\n")
        sys.exit(1)
    if proc.returncode != 0:
        sys.stderr.write(f"fatal: {what} failed (exit {proc.returncode})\n")
        sys.stderr.write(proc.stderr)
        sys.exit(1)
    return proc


def main():
    with tempfile.TemporaryDirectory(prefix="pcre2-probe-") as td:
        root = Path(td)
        (root / "Cargo.toml").write_text(CARGO_TOML, encoding="utf-8")
        (root / "build.rs").write_text(BUILD_RS, encoding="utf-8")
        (root / "src").mkdir()
        (root / "src" / "main.rs").write_text(MAIN_RS, encoding="utf-8")

        env = dict(os.environ)
        env["CARGO_TERM_COLOR"] = "never"
        env["CARGO_HOME"] = str(root / "cargo-home")
        env["CARGO_TARGET_DIR"] = str(root / "target")
        env["PCRE2_SYS_STATIC"] = "1"
        proc = run_or_die(
            ["cargo", "run", "--quiet"],
            str(root),
            "cargo run (bundled PCRE2 build)",
            env,
        )
        try:
            result = json.loads(proc.stdout)
        except json.JSONDecodeError as exc:
            sys.stderr.write(f"fatal: probe program output was not one JSON object: {exc}\n")
            sys.stderr.write(proc.stdout)
            sys.exit(1)
        if not isinstance(result, dict):
            sys.stderr.write("fatal: probe program output was not a JSON object\n")
            sys.stderr.write(proc.stdout)
            sys.exit(1)

        result["script"] = "probe_pcre2.py"
        result["regex_crate_pin"] = REGEX_PIN
        result["pcre2_sys_crate_pin"] = PCRE2_SYS_PIN
        print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
